"""Blueprint file writer preparation."""

from __future__ import annotations

from pathlib import Path

from .models import Blueprint, BlueprintOutput, BlueprintWriteTarget


class BlueprintWriter:
    """Render structured blueprints into safe file targets."""

    FILENAMES = (
        "SYSTEM_DESIGN.md",
        "BACKEND_ARCHITECTURE.md",
        "FRONTEND_ARCHITECTURE.md",
        "DATABASE_DESIGN.md",
        "API_FLOW.md",
        "IMPLEMENTATION_PLAN.md",
        "FOLDER_STRUCTURE.md",
        "DEPENDENCIES.md",
    )

    def prepare(
        self,
        output_directory: Path,
        output: BlueprintOutput,
    ) -> list[BlueprintWriteTarget]:
        """Return all blueprint file targets and rendered content."""
        if output.blueprint is None:
            raise ValueError("BlueprintWriter requires a generated blueprint")

        output_directory = output_directory.resolve()
        files = self._render_files(output.blueprint)
        return [
            BlueprintWriteTarget(path=output_directory / filename, content=content)
            for filename, content in files.items()
        ]

    def conflicts(
        self,
        targets: list[BlueprintWriteTarget],
        overwrite: bool,
    ) -> list[Path]:
        """Return existing files that would be overwritten without permission."""
        if overwrite:
            return []
        return [target.path for target in targets if target.path.exists()]

    def _render_files(self, blueprint: Blueprint) -> dict[str, str]:
        return {
            "SYSTEM_DESIGN.md": self._document(
                "System Design",
                [
                    ("Title", blueprint.title),
                    ("Summary", blueprint.summary),
                    ("System Design", blueprint.system_design),
                ],
            ),
            "BACKEND_ARCHITECTURE.md": self._document(
                "Backend Architecture",
                [
                    ("Backend Architecture", blueprint.backend_architecture),
                ],
            ),
            "FRONTEND_ARCHITECTURE.md": self._document(
                "Frontend Architecture",
                [
                    ("Frontend Architecture", blueprint.frontend_architecture),
                ],
            ),
            "DATABASE_DESIGN.md": self._document(
                "Database Design",
                [
                    ("Database Design", blueprint.database_design),
                ],
            ),
            "API_FLOW.md": self._document(
                "API Flow",
                [
                    ("API Flow", blueprint.api_flow),
                ],
            ),
            "IMPLEMENTATION_PLAN.md": self._document(
                "Implementation Plan",
                [
                    ("Implementation Plan", blueprint.implementation_plan),
                ],
            ),
            "FOLDER_STRUCTURE.md": self._document(
                "Folder Structure",
                [
                    ("Folder Structure", blueprint.folder_structure),
                ],
            ),
            "DEPENDENCIES.md": self._document(
                "Dependencies",
                [
                    ("Dependencies", blueprint.dependencies),
                ],
            ),
        }

    @staticmethod
    def _document(title: str, sections: list[tuple[str, str]]) -> str:
        lines = [f"# {title}", ""]
        for heading, body in sections:
            lines.extend([f"## {heading}", "", body.strip(), ""])
        lines.append("Generated by BlueprintAgent V1.")
        return "\n".join(lines).rstrip() + "\n"
