"""Bootstrap project templates."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(slots=True, frozen=True)
class ProjectTemplates:
    """
    Collection of reusable project templates.

    BootstrapGenerator uses these templates to
    populate scaffolded files.
    """

    README: str = """# Project Name

## Overview

Describe your project here.

---

## Project Structure

frontend/
backend/
docker/
kubernetes/
docs/

---

## Getting Started

Coming soon.

---

Generated by Sohail-Agent-CLI
"""

    GITIGNORE: str = """# Python
__pycache__/
*.py[cod]
.pytest_cache/
venv/

# Environment
.env

# macOS
.DS_Store

# IDE
.vscode/
.idea/

# Build
dist/
build/
*.egg-info/
"""

    ENV_EXAMPLE: str = """# Environment Variables

APP_NAME=

APP_ENV=development

APP_PORT=

DATABASE_URL=

SECRET_KEY=
"""

    MAKEFILE: str = """install:
\tpip install -r requirements.txt

test:
\tpytest

lint:
\techo "Add linter"

format:
\techo "Add formatter"

run:
\techo "Start application"
"""

    LICENSE: str = """MIT License

Copyright (c)

Permission is hereby granted, free of charge,
to any person obtaining a copy of this software...
"""

    @classmethod
    def as_dict(cls) -> dict[str, str]:
        """
        Return all templates keyed by filename.
        """

        template = cls()

        return {
            "README.md": template.README,
            ".gitignore": template.GITIGNORE,
            ".env.example": template.ENV_EXAMPLE,
            "Makefile": template.MAKEFILE,
            "LICENSE": template.LICENSE,
        }