from pathlib import Path

import pytest

from sohail_agent_cli.blueprint import BlueprintLoader, BlueprintOutput, BlueprintWriter
from sohail_agent_cli.blueprint.models import Blueprint
from sohail_agent_cli.bootstrap.validator import PlanningValidationError


def write_plan(root: Path) -> Path:
    plan = root / "project-plan"
    decisions = plan / "decisions"
    decisions.mkdir(parents=True)
    (plan / "REQUIREMENTS.md").write_text(
        """---
project: Shopfront
---

# Requirements

## Project Goal

Build ecommerce platform.
""",
        encoding="utf-8",
    )
    (plan / "ARCHITECTURE.md").write_text("# Architecture\n", encoding="utf-8")
    (plan / "TASK.md").write_text("# Task Plan\n", encoding="utf-8")
    (decisions / "001_frontend.md").write_text(
        "# DEC-001\n\n## Decision\n\nReact\n", encoding="utf-8"
    )
    return plan


def write_specs(root: Path) -> Path:
    specs = root / "specifications"
    specs.mkdir()
    (specs / "PRODUCT_SPEC.md").write_text("# Product Specification\n", encoding="utf-8")
    (specs / "FEATURES.md").write_text("# Features\n- Browse products\n", encoding="utf-8")
    (specs / "DATA_MODEL.md").write_text("# Data Model\nProduct\n", encoding="utf-8")
    (specs / "API_SPEC.md").write_text("# API Specification\nGET /products\n", encoding="utf-8")
    (specs / "NON_FUNCTIONAL.md").write_text("# NFR\nNo secrets\n", encoding="utf-8")
    return specs


def blueprint() -> Blueprint:
    return Blueprint(
        title="Shopfront",
        summary="Commerce platform blueprint.",
        system_design="Layered system.",
        backend_architecture="FastAPI service.",
        frontend_architecture="React application.",
        database_design="PostgreSQL schema.",
        api_flow="GET /products",
        implementation_plan="Build slices.",
        folder_structure="src/, tests/",
        dependencies="fastapi, react",
    )


def test_blueprint_loader_reads_complete_plan_and_specs(tmp_path):
    loaded = BlueprintLoader().load(write_plan(tmp_path), write_specs(tmp_path))

    assert loaded.plan_directory == (tmp_path / "project-plan").resolve()
    assert loaded.specification_directory == (tmp_path / "specifications").resolve()
    assert loaded.project_goal == "Build ecommerce platform."
    assert loaded.decisions[0].topic == "frontend"
    assert "Browse products" in loaded.features_markdown
    assert "GET /products" in loaded.api_spec_markdown


def test_blueprint_loader_rejects_invalid_plan(tmp_path):
    with pytest.raises(PlanningValidationError):
        BlueprintLoader().load(tmp_path / "missing-plan", write_specs(tmp_path))


def test_blueprint_loader_rejects_invalid_specs(tmp_path):
    with pytest.raises(ValueError, match="Specification package not found"):
        BlueprintLoader().load(write_plan(tmp_path), tmp_path / "missing-specs")


def test_blueprint_writer_prepares_all_required_files(tmp_path):
    output = BlueprintOutput(blueprint=blueprint())

    targets = BlueprintWriter().prepare(tmp_path, output)
    names = [target.path.name for target in targets]

    assert names == [
        "SYSTEM_DESIGN.md",
        "BACKEND_ARCHITECTURE.md",
        "FRONTEND_ARCHITECTURE.md",
        "DATABASE_DESIGN.md",
        "API_FLOW.md",
        "IMPLEMENTATION_PLAN.md",
        "FOLDER_STRUCTURE.md",
        "DEPENDENCIES.md",
    ]
    assert all(target.content.endswith("\n") for target in targets)
    assert "# System Design" in targets[0].content
    assert "Generated by BlueprintAgent V1." in targets[0].content


def test_blueprint_writer_detects_conflicts(tmp_path):
    target = tmp_path / "SYSTEM_DESIGN.md"
    target.write_text("existing", encoding="utf-8")
    targets = BlueprintWriter().prepare(
        tmp_path,
        BlueprintOutput(blueprint=blueprint()),
    )

    conflicts = BlueprintWriter().conflicts(targets, overwrite=False)

    assert conflicts == [target.resolve()]
