"""Specification file writer preparation."""

from __future__ import annotations

from pathlib import Path

from .models import Specification, SpecificationOutput, SpecificationWriteTarget


class SpecificationWriter:
    """Render structured specifications into safe file targets."""

    FILENAMES = (
        "PRODUCT_SPEC.md",
        "FEATURES.md",
        "DATA_MODEL.md",
        "API_SPEC.md",
        "NON_FUNCTIONAL.md",
    )

    def prepare(
        self,
        output_directory: Path,
        output: SpecificationOutput,
    ) -> list[SpecificationWriteTarget]:
        """Return all specification file targets and rendered content."""
        if output.specification is None:
            raise ValueError("SpecificationWriter requires a generated specification")

        output_directory = output_directory.resolve()
        files = self._render_files(output.specification)
        return [
            SpecificationWriteTarget(path=output_directory / filename, content=content)
            for filename, content in files.items()
        ]

    def conflicts(
        self,
        targets: list[SpecificationWriteTarget],
        overwrite: bool,
    ) -> list[Path]:
        """Return existing files that would be overwritten without permission."""
        if overwrite:
            return []
        return [target.path for target in targets if target.path.exists()]

    def _render_files(self, specification: Specification) -> dict[str, str]:
        return {
            "PRODUCT_SPEC.md": self._document(
                "Product Specification",
                [
                    ("Title", specification.title),
                    ("Summary", specification.summary),
                    ("Product Scope", specification.product_spec),
                ],
            ),
            "FEATURES.md": self._document(
                "Features",
                [
                    ("Feature List", self._bullets(specification.features)),
                ],
            ),
            "DATA_MODEL.md": self._document(
                "Data Model",
                [
                    ("Data Model", specification.data_model),
                ],
            ),
            "API_SPEC.md": self._document(
                "API Specification",
                [
                    ("API Surface", specification.api_spec),
                ],
            ),
            "NON_FUNCTIONAL.md": self._document(
                "Non-Functional Requirements",
                [
                    ("Requirements", self._bullets(specification.non_functional)),
                ],
            ),
        }

    @staticmethod
    def _document(title: str, sections: list[tuple[str, str]]) -> str:
        lines = [f"# {title}", ""]
        for heading, body in sections:
            lines.extend([f"## {heading}", "", body.strip(), ""])
        lines.append("Generated by SpecificationAgent V1.")
        return "\n".join(lines).rstrip() + "\n"

    @staticmethod
    def _bullets(items: tuple[str, ...]) -> str:
        if not items:
            return "- None provided."
        return "\n".join(f"- {item}" for item in items)
